services:
  db:
    image: postgres:16
    container_name: proxy_postgres
    restart: always
    environment:
      POSTGRES_DB: proxy_db
      POSTGRES_USER: proxy_user
      POSTGRES_PASSWORD: proxy_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: proxy_redis
    restart: always

  backend:
    build: .
    container_name: proxy_backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis

  celery:
    build: .
    container_name: proxy_celery
    command: celery -A config worker --loglevel=info
    volumes:
      - ./backend:/app/backend
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: proxy_frontend
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data: